Repository Open-Source-Chandigarh/MeTube, pull requests merged in 2024-10, with the labels that each got.

#12 Fixes Issue #8
  index.html
  script.js
  style.css
Labels: hacktober, hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#20 fix:fixes issue #9
  script.js
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#16 Added favicon
  favicon/android-chrome-192x192.png
  favicon/android-chrome-512x512.png
  favicon/apple-touch-icon.png
  favicon/favicon-16x16.png
  favicon/favicon-32x32.png
  favicon/favicon.ico
  favicon/site.webmanifest
  index.html
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#25 fixed issue #21
  LEARN.md
Labels: hacktoberfest, hacktoberfest-accepted

#23 Fixed Dark mod in Header and Default Video layout
  style.css
Labels: hacktoberfest2024, hacktoberfest-accepted

#28 Fixed issue_26
  .vscode/settings.json
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#29 fix: fixes Issue_#27
  style.css
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#31 Footer added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#33 Addition of Meta Tags to boost seo for x and fb
  index.html
Labels: hacktoberfest, hacktoberfest-accepted
